#!/usr/bin/env python
import sys
from optparse import OptionParser
import csv
try:
    import json
except ImportError:
    import simplejson as json

parser = OptionParser()
options, args = parser.parse_args()

csv_file = open(args[0]) if args else sys.stdin
reader = csv.DictReader(csv_file, delimiter="\t")
rows = list(reader)
start = 'curl -H "Content-type:application/json" -X POST "http://localhost:8080/api/dataverses/'
for row in rows:
    row["permissionRoot"] = "false"
    parent = row["parent"]
    parts = parent.split("/")
    target = parts[-1] if parts[1] else "root"
    del row["parent"]
    creator = row["creator"]
    del row["creator"]
    # FIXME: don't simply strip out single quotes
    row["description"] = row["description"].replace("'", "")
    jsondata = "%s%s%s" % ("'",json.dumps(row),"'")
    row["permissionRoot"] = "false"
    row["permissionRoot"] = "false"
    print
csv_file.close()
